#!/usr/bin/env python3
# PS5 AT9 Converter - Generate the ATRAC9 tables from LibAtrac9.
# Copyright (C) 2026 BlackBearReloaded
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate ps5at9/atrac9_tables.py from the LibAtrac9 source tree.

Usage: tools/gen_atrac9_tables.py /path/to/LibAtrac9 > ps5at9/atrac9_tables.py

LibAtrac9 (https://github.com/Thealexbarney/LibAtrac9) is MIT licensed,
Copyright (c) 2018 Alex Barney. Only its constant tables are converted.
"""

import re
import sys
from pathlib import Path

NUMBER = re.compile(r"[+-]?(?:0[xX][0-9a-fA-F]+|\d+\.\d*(?:[eE][+-]?\d+)?|\d+(?:[eE][+-]?\d+)?)")


def parse_initializer(text):
    """Convert a C# array initializer into nested Python lists."""
    text = re.sub(r"new\s*(?:byte|short|int|double)?\s*\[\]", "", text)
    out = []
    stack = [out]
    pos = 0
    while pos < len(text):
        ch = text[pos]
        if ch == "{":
            child = []
            stack[-1].append(child)
            stack.append(child)
            pos += 1
        elif ch == "}":
            stack.pop()
            pos += 1
        elif ch in " \t\r\n,":
            pos += 1
        else:
            m = NUMBER.match(text, pos)
            if not m:
                raise ValueError("unexpected token near: " + text[pos:pos + 40])
            tok = m.group(0)
            if tok.lower().lstrip("+-").startswith("0x"):
                value = int(tok, 16)
            elif "." in tok or "e" in tok.lower():
                value = float(tok)
            else:
                value = int(tok, 10)
            stack[-1].append(value)
            pos = m.end()
    assert len(out) == 1
    return out[0]


def arrays(source):
    result = {}
    pattern = re.compile(r"static\s+readonly\s+[\w\[\]]+\s+(\w+)\s*=\s*(\{.*?\});", re.S)
    for name, body in pattern.findall(source):
        if re.search(r"(?<![\w.+-])[A-Za-z_]\w*\s*[,}]", re.sub(r"new\s*\w*\s*\[\]", "", body).replace("null", "0")):
            continue  # references to other arrays; rebuilt below
        result[name] = parse_initializer(body)
    return result


def fmt(values, indent="    ", width=100):
    items = [repr(v) for v in values]
    lines, line = [], indent
    for item in items:
        piece = item + ", "
        if len(line) + len(piece) > width:
            lines.append(line.rstrip())
            line = indent
        line += piece
    lines.append(line.rstrip())
    return "[\n" + "\n".join(lines) + "\n" + indent[:-4] + "]"


def main():
    root = Path(sys.argv[1]) / "CSharp" / "LibAtrac9"
    huff = arrays((root / "HuffmanCodebooks.cs").read_text(encoding="utf-8-sig"))
    bex = arrays((root / "BandExtension.cs").read_text(encoding="utf-8-sig"))
    sfw = arrays((root / "ScaleFactors.cs").read_text(encoding="utf-8-sig"))
    alloc = (root / "BitAllocation.cs").read_text(encoding="utf-8-sig")
    main_curve = parse_initializer(re.search(r"byte\[\]\s+main\s*=\s*(\{.*?\});", alloc, re.S).group(1))

    out = []
    w = out.append
    w("# PS5 AT9 Converter - ATRAC9 constant tables converted from LibAtrac9.")
    w("# Copyright (c) 2018 Alex Barney")
    w("# SPDX-License-Identifier: MIT")
    w("")
    w('"""ATRAC9 constant tables.')
    w("")
    w("Generated by tools/gen_atrac9_tables.py from LibAtrac9")
    w("(https://github.com/Thealexbarney/LibAtrac9). Do not edit by hand. The MIT")
    w("License text is in third_party/LibAtrac9.LICENSE.txt.")
    w('"""')
    w("")
    w("# Scale factor codebooks: {word length: (bits, codes)}")
    w("SF_UNSIGNED = {")
    for n in range(1, 7):
        w(f"    {n}: ({fmt(huff[f'ScaleFactorsA{n}Bits'], ' ' * 8)}, {fmt(huff[f'ScaleFactorsA{n}Codes'], ' ' * 8)}),")
    w("}")
    w("")
    w("SF_SIGNED = {")
    for n in range(2, 6):
        w(f"    {n}: ({fmt(huff[f'ScaleFactorsB{n}Bits'], ' ' * 8)}, {fmt(huff[f'ScaleFactorsB{n}Codes'], ' ' * 8)}),")
    w("}")
    w("")
    groups_a = huff["HuffmanSpectrumAGroupSizes"]
    groups_b = huff["HuffmanSpectrumBGroupSizes"]
    w("# Spectrum codebooks: {(codebook set, word length, codebook index): (value count power, bits, codes)}")
    w("SPECTRUM = {")
    for wl in range(2, 8):
        for cbi in range(4):
            name = f"SpectrumA{wl}{cbi + 1}"
            w(f"    (0, {wl}, {cbi}): ({groups_a[wl][cbi]}, {fmt(huff[name + 'Bits'], ' ' * 8)}, {fmt(huff[name + 'Codes'], ' ' * 8)}),")
    for wl in range(2, 8):
        for cbi in range(1, 4):
            name = f"SpectrumB{wl}{cbi + 1}"
            w(f"    (1, {wl}, {cbi}): ({groups_b[wl][cbi]}, {fmt(huff[name + 'Bits'], ' ' * 8)}, {fmt(huff[name + 'Codes'], ' ' * 8)}),")
    w("}")
    w("")
    w("SF_WEIGHTS = [")
    for row in sfw["ScaleFactorWeights"]:
        w(f"    {row},")
    w("]")
    w("")
    w(f"GRADIENT_MAIN = {main_curve}")
    w("")
    w(f"BEX_GROUP_INFO = {bex['BexGroupInfo']}")
    w(f"BEX_VALUE_COUNTS = {bex['BexEncodedValueCounts']}")
    w(f"BEX_DATA_LENGTHS = {bex['BexDataLengths']}")
    for name, py in (("BexMode0Bands3", "BEX_MODE0_BANDS3"), ("BexMode0Bands4", "BEX_MODE0_BANDS4"),
                     ("BexMode0Bands5", "BEX_MODE0_BANDS5")):
        w(f"{py} = [")
        for row in bex[name]:
            w(f"    {fmt(row, ' ' * 8)},")
        w("]")
    for name, py in (("BexMode2Scale", "BEX_MODE2_SCALE"), ("BexMode3Initial", "BEX_MODE3_INITIAL"),
                     ("BexMode3Rate", "BEX_MODE3_RATE"), ("BexMode4Multiplier", "BEX_MODE4_MULTIPLIER")):
        w(f"{py} = {fmt(bex[name])}")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
