#!/usr/bin/env python3
# PS5 AT9 Converter - Generate the MP3 tables from PDMP3 and minimp3.
# Copyright (C) 2026 BlackBearReloaded
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate ps5at9/mp3_tables.py.

Usage: tools/gen_mp3_tables.py /path/to/PDMP3/pdmp3.c /path/to/minimp3/minimp3.h > ps5at9/mp3_tables.py

Sources (both public domain):
- PDMP3 by Krister Lagerstrom (Unlicense): Huffman code trees and the
  synthesis window of ISO/IEC 11172-3.
- minimp3 by lieff (CC0 1.0): scale factor band widths for all MPEG-1,
  MPEG-2 and MPEG-2.5 sample rates.
"""

import re
import sys


def c_array(source, name):
    m = re.search(name + r"\s*\[[^\]]*\](?:\s*\[[^\]]*\])?\s*=\s*\{(.*?)\};", source, re.S)
    if not m:
        raise SystemExit("array not found: " + name)
    body = re.sub(r"//[^\n]*", "", m.group(1))
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    return [float(t.rstrip("f")) if ("." in t or "e" in t.lower()) and not t.lower().startswith("0x")
            else int(t, 0) for t in re.findall(r"[-+]?(?:0[xX][0-9a-fA-F]+|\d+\.?\d*(?:[eE][-+]?\d+)?f?)", body)]


def tree_codes(table, start, treelen):
    """Enumerate (code, length, value) from a PDMP3/dist10 Huffman tree."""
    out = []

    def walk(point, code, length):
        if length > 24:
            raise SystemExit("runaway tree")
        entry = table[start + point]
        if entry & 0xFF00 == 0:
            out.append((code, length, entry & 0xFF))
            return
        for bit in (0, 1):
            p = point
            if bit:
                while (table[start + p] & 0xFF) >= 250:
                    p += table[start + p] & 0xFF
                p += table[start + p] & 0xFF
            else:
                while (table[start + p] >> 8) >= 250:
                    p += table[start + p] >> 8
                p += table[start + p] >> 8
            if p < treelen:
                walk(p, (code << 1) | bit, length + 1)

    walk(0, 0, 0)
    return out


def main():
    pd = open(sys.argv[1], encoding="latin-1").read()
    mm = open(sys.argv[2], encoding="latin-1").read()
    table = c_array(pd, "g_huffman_table")
    main_tab = re.search(r"g_huffman_main\s*\[34\]\s*=\s*\{(.*?)\};", pd, re.S).group(1)
    rows = re.findall(r"\{\s*(NULL|g_huffman_table\s*(?:\+\s*\d+)?)\s*,\s*(\d+)\s*,\s*(\d+)\s*\}", main_tab)
    assert len(rows) == 34
    synth = c_array(pd, "g_synth_dtbl")
    assert len(synth) == 512
    scf_long = c_array(mm, "g_scf_long")
    scf_short = c_array(mm, "g_scf_short")
    assert len(scf_long) == 8 * 23 and len(scf_short) == 8 * 40

    w = sys.stdout.write
    w("# PS5 AT9 Converter - MP3 constant tables converted from PDMP3 and minimp3.\n")
    w("# SPDX-License-Identifier: Unlicense AND CC0-1.0\n\n")
    w('"""MPEG audio layer III constant tables.\n\n')
    w("Generated by tools/gen_mp3_tables.py. Huffman trees and the synthesis window\n")
    w("come from PDMP3 (Krister Lagerstrom, Unlicense/public domain); scale factor\n")
    w('band widths come from minimp3 (lieff, CC0 1.0). Do not edit by hand.\n"""\n\n')
    w("# {table: (linbits, [(code, length, x, y), ...])}; table 32/33 values are packed vwxy\n")
    w("HUFFMAN = {\n")
    for num, (ptr, treelen, linbits) in enumerate(rows):
        if num == 33:
            continue
        if ptr == "NULL":
            continue
        start = int(ptr.split("+")[1]) if "+" in ptr else 0
        codes = tree_codes(table, start, int(treelen))
        entries = ", ".join("(%d, %d, %d, %d)" % (c, l, v >> 4, v & 15) for c, l, v in sorted(codes, key=lambda t: (t[1], t[0])))
        w("    %d: (%s, [%s]),\n" % (num, linbits, entries))
    # Count1 table B: fixed 4-bit codes, codeword = 15 - value.
    w("    33: (0, [%s]),\n" % ", ".join("(%d, 4, %d, %d)" % (15 - v, v >> 4, v & 15) for v in range(16)))
    w("}\n\n")
    w("SYNTH_WINDOW = [\n")
    for i in range(0, 512, 8):
        w("    " + ", ".join(repr(v) for v in synth[i:i + 8]) + ",\n")
    w("]\n\n")
    # minimp3 row order: 11025/12000, 8000, 22050, 24000, 16000, 44100, 48000, 32000
    rates = {11025: 0, 12000: 0, 8000: 1, 22050: 2, 24000: 3, 16000: 4, 44100: 5, 48000: 6, 32000: 7}
    w("# Scale factor band boundaries: {sample_rate: (long[23], short[14])}\n")
    w("SFB = {\n")
    for rate, row in sorted(rates.items()):
        longw = scf_long[row * 23:row * 23 + 22]
        shortw = scf_short[row * 40:row * 40 + 39:3]
        lb, sb = [0], [0]
        for v in longw:
            lb.append(lb[-1] + v)
        for v in shortw:
            sb.append(sb[-1] + v)
        assert lb[-1] == 576 and sb[-1] == 192, (rate, lb, sb)
        w("    %d: (%s, %s),\n" % (rate, lb, sb))
    w("}\n")


if __name__ == "__main__":
    main()
